language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - python --version
  - pip --version
  # command to install dependencies
  - pip install coveralls coverage
  - pip install .
# command to run tests
script:
  - coverage run --include=htrc/* setup.py test
  - coverage report
after_success: coveralls
